### ISSUE TITLE
__qp_activation undefined in different sources

### ISSUE THREAD

**Issue by curcio** [google/qpp#114] opened 2013-03-13 23:08 UTC
When trying to use the demo with knockout I came with up with a problem that __qp_activation is not defined.

In knockout.js.js when checking if a property is being traced there is a line that reads:

if (window.__qp.isTraced(((__qp_activation._44022_12 = window.__qp.trace(__qp_44022_12)), __qp_44022_12))) window.__qp.propertyChanges[__qp_44022_12].push({

__qp_actication is undefined, so __qp_activation._44022_12 results in an error.

Changing activationId in GlobalSymbols from __qp_activation to window.__qp_activation fixes the error, but introduces the an error when the variable is declared:
var window.__qp_activation =  {turn: window.__qp.turn};
(invalid syntax . not expected)

Changing line 151 in QPTreeWriter.js from activationId to '__qp_activation' fixes this error and allows the demo with knockout to run when tracing a simple property.

**Comment by johnjbarton** [comment] 2013-03-14 00:03
__qp_activation is a local var per function. In last change demo look at demo.js.js to see how it is defined.

Then look at the knockout generated code to see what is different.

**Comment by curcio** [comment] 2013-03-14 16:44
I tried to follow it but now I'm not sure if it's a problem in traceur or querypoint. The variable doesn't get declared in the function.

I'll push the test where the problem is present 9a94994c47f916c554f6d4472a291f07d9b3899a . The test behaves similar to the original demo, when you press the button, the message says it's been clicked 0 times and if you comment out the line that sets obj.prop to 0, the click counter starts working.

To reproduce the issue open test/kodemo/qpd.html
Start querypoint debugger and apply last change to condition.value in line 36
Press the button 'Try me' in the debuggee and error message appears:
Uncaught TypeError: Cannot set property '_44022_12' of undefined knockout-2.2.0rc.debug.js.js:1587

**Comment by johnjbarton** [comment] 2013-03-18 14:58
I am unable to run kodemo.qpd.html because of this error:
Uncaught Error: Unable to parse bindings.
Message: ReferenceError: selectLast is not defined;
Bindings value: foreach: {data: loads, afterAdd: selectLast}

selectLast only appears in the the html. Maybe another change was not committed?

**Comment by curcio** [comment] 2013-03-18 15:19
At the moment I'm having other problems with qpp and can't try this, but it was working ok. In master branch Panel/Log/LogScrubber.js has the function selectLast defined in line 504. LogScrubbers is binded in that context so it should be working

**Comment by johnjbarton** [comment] 2013-03-18 15:41
yep, sorry. I guess I did not reload my qpp fully.

**Comment by johnjbarton** [comment] 2013-03-18 15:54
Looks like QPFunctionPreambleTransformer is not operating on function
expressions even though I thought both FunctionDeclaration and
FunctionExpression call transformFunctionBody.  Notice two functions
without preambles:

var __qp_45061_1503 = function(initialValue) {
var _latestValue = initialValue;
function observable() {
if (arguments["length"] > 0) {
if ((!observable['equalityComparer']) || !observable['equalityComparer'](_latestValue, arguments[0])) {
observable["valueWillMutate"]();
_latestValue = arguments[0];
var __qp_44009_10 = observable;
var __qp_44022_12 = "_latestValue";
var __qp_44037_12 = _latestValue;
if (window.__qp.isTraced(((__qp_activation._44022_12 = window.__qp.trace(
__qp_44022_12)), __qp_44022_12))) window.__qp.propertyChanges[__qp_44022_12
].push({
Uncaught TypeError: Cannot set property '_44022_12' of undefined

The next step would be to create a demoFunctionExpression.js test case that
reproduces the problem within the demo.js like size.  Just needs a var foo
= function() {} example loke the __qp_45061_1503 example and one like the
function observable(){}, a function defined within a function.

**Comment by curcio** [comment] 2013-03-18 17:21
Added a test case in a seperate directory test/functionExpressions

When applying lastChange to obj.prop a different error message appears than the one reported in this issue, but __qp_activation isn't defined in function updateButton

**Closed as completed** 2013-03-18 23:28 UTC
