### ISSUE TITLE
Load scripts only one time.

### ISSUE THREAD

**Issue by curcio** [google/qpp#4] opened 2013-01-14 21:26 UTC
Using demo.js when pressing lastChange on obj.prop on line 23, scripts get reloaded and the html appears with 3 buttons.
I'm guessing this is because we're appending two buttons to the current html(one for each script). On the other hand, sometimes no button appears.

Don't know exactly how to reproduce. I get the 3 buttons quite frequently, and the no button is a little rare.

**Comment by johnjbarton** [comment] 2013-01-15 00:02
I believe that the three button issue is caused by the current bogus script re-writing: we first reload the page and let the script tags be compiled and run (button injected) then we insert script tags with our re-written JS for lastChange. (button injected). I would expect two, so three is still a mystery.  Zero could mean the load simply failed.

The fix is to use a new WebKit feature that landed Friday:
https://bugs.webkit.org/show_bug.cgi?id=104384
I'll work on that this week.

**Comment by johnjbarton** [comment] 2013-01-30 23:33
Fixed by 32ffede71a3e629e6edb9bfefc744087314da801

**Comment by johnjbarton** [comment] 2013-02-01 18:50
There is more work here: the QPRuntime has code to deal with the original JS which we are now blocking.

**Closed as completed** 2013-02-01 19:13 UTC
